"$schema" = "https://ubcode.useblocks.com/ubproject.schema.json"

[rst_lint]
ignore = ["block.title_line"]

[needs]
id_required = true

[[needs.types]]
directive = "feature"
title = "Feature"
prefix = "FEAT_"
color = "#Gold"
style = "rectangle"

[[needs.types]]
directive = "usecase"
title = "Use Case"
prefix = "USE_"
color = "#Thistle"
style = "rectangle"

[[needs.types]]
directive = "fault"
title = "Fault"
prefix = "FAULT_"
color = "#Pink"
style = "rectangle"

[[needs.types]]
directive = "impl"
title = "Implementation"
prefix = "IMPL_"
color = "#LightGreen"
style = "node"

[[needs.types]]
directive = "test"
title = "Test"
prefix = "TEST_"
color = "#DarkTurquoise"
style = "node"

[parse.extend_directives.src-trace]
argument = false
options = true
content = false
content_required = false
parse_content = false
description = "A directive to generate need items from one-line definition"
extension = "sphinx-codelinks"                                              # The extension that provides the directive

[parse.extend_directives.video]
argument = true
content = false
options = true

[parse.extend_directives.tabs]
argument = true
content = true
options = true

[parse.extend_directives.typer]
argument = true
content = true
options = true

[parse.extend_directives.button-ref]
argument = true
content = true
options = true

[parse.extend_directives.button-link]
argument = true
content = true
options = true
